### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ddsydney** [superwebshare/super-web-share-wordpress-plugin#1]
Hi,  I wanted to let you know I installed your plugin today on my website www.sheerdropwines.com and it seemed to work fine for a while then stopped working on my Macbook with Chrome.  It still works with other devices (including Safari on the same MacBook).

Any suggestions?

Also emails aren't working to your contact@superwebshare.com...

**Comment by superwebshareteam** [comment]
Hey @ddsydney,

First of all, sorry for the delay in responding here as we were not not checking this GitHub repository as the development repo is a different one.

Our plugin shows the prompt within supported devices, and from the last version 2.0 we are now showing a fallback if the browser is not supporting the Share API. So could you please check the browser again and let us know whether its working fine or not? Make sure that the fallback is enabled. 

**About the email:** We changed that email to support@superwebshare.com to handle the support mails more effectively. We hope you will mail to our new email, so that we can talk more about the plugin.

Thanks in advance :)

**Comment by superwebshareteam** [comment]
Closing this issue as we didn't get any responses and the issues reported are already fixed.
